#  Creation: Gerard Forns (22/05/2021)

- name: Install nginx PHP PHP-FPM
  hosts: web
  become: true


  # Install Software
  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Install REMI repo
    yum:
      name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
      state: present
  
  - name: Install yum-utils
    yum:
      name: yum-utils 
      state: present

  - name: Enable PHP 7.4 REMI repository
    command: yum-config-manager --enable remi-php74

  - name: Install PHP 7.4 php-fpm
    yum:
      name: 
        - php 
        - php-common 
        - php-opcache 
        - php-mcrypt 
        - php-cli 
        - php-gd 
        - php-curl 
        - php-mysql 
        - php-fpm
      state: present


  # Nginx Configuration
  - name: Configure nginx to run .php files
    template:
      src: templates/php.conf
      dest: "/etc/nginx/default.d/php.conf"

  - name: Create a phpinfo file
    template:
      src: templates/phpinfo.php
      dest: "/usr/share/nginx/html/phpinfo.php"


  # PHP Configuration (/etc/php.ini)
  - name: modify /etc/php.ini
    ini_file:
      path: /etc/php.ini
      section: PHP
      option: "{{ item.option }}" 
      value: "{{ item.value }}"
      backup: yes
    with_items:
      - { option: 'memory_limit', value: '2G' }
      - { option: 'max_execution_time', value: '1800' }
      - { option: 'zlib.output_compression', value: 'On' }
      - { option: 'cgi.fix_pathinfo', value: '0' }
      - { option: 'session.save_path', value: '"/var/lib/php/session"' }
  

   # PHP-FPM  Configuration (/etc/php-fpm.d/www.conf)
  - name: modify /etc/php-fpm.d/www.conf
    ini_file:
      path: /etc/php-fpm.d/www.conf
      section: www
      option: "{{ item.option }}" 
      value: "{{ item.value }}"
      backup: yes
    with_items:
      - { option: 'user', value: 'nginx' }
      - { option: 'group', value: 'nginx' }
      - { option: 'listen', value: '/run/php-fpm/php-fpm.sock' }
      - { option: 'listen.owner' , value: 'nginx' }
      - { option: 'listen.group', value: 'nginx' }
      - { option: 'listen.mode', value: '0660' }
      - { option: 'env[HOSTNAME]', value: '$HOSTNAME' }
      - { option: 'env[PATH]', value: '/usr/local/bin:/usr/bin:/bin' }
      - { option: 'env[TMP]', value: '/tmp' }
      - { option: 'env[TMPDIR]', value: '/tmp' }
      - { option: 'env[TEMP]', value: '/tmp' }

      
  # PHP-FPM Filesystem modifications
  - name: Create direcories, if not exist
    file:
      path: "{{ item.folder }}"
      state: directory
    with_items:
      - { folder: '/var/lib/php/session/' }
      - { folder: '/run/php-fpm/' }

  - name: Modify permissions
    file:
      path: "{{ item.folder }}"
      state: directory
      recurse: yes
      owner: nginx
      group: nginx
    with_items:
      - { folder: '/var/lib/php/' }
      - { folder: '/run/php-fpm/' }



  # Start / Enable Services
  - name: Start nginx
    service:
      name: nginx
      state: started

  - name: Enable nginx
    service:
      name: nginx
      enabled: yes

  - name: Start php-fpm
    service:
      name: php-fpm
      state: started

  - name: Enable php-fpm
    service:
      name: php-fpm
      enabled: yes


  # Modify firewall
  - name: permit HTTP traffic on firewalld
    firewalld:
      service: http
      permanent: yes
      state: enabled
      immediate: yes

